apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-pod-vips
  namespace: cassandra

data:
  cassandra-dc1-rack1-sts-0: "192.168.100.101"
  cassandra-dc1-rack1-sts-1: "192.168.100.102"
  cassandra-dc1-rack1-sts-2: "192.168.100.103"
  cassandra-dc1-rack1-sts-3: "192.168.100.104"
  cassandra-dc1-rack1-sts-4: "192.168.100.105"
